using BuildingBlocks.Tools.Models;
using System.Text;

namespace BuildingBlocks.Tools.Services;

/// <summary>
/// Generates .env file content from options classes.
/// </summary>
internal class EnvFileGenerator
{
    /// <summary>
    /// Generates .env file content from a list of options classes.
    /// </summary>
    /// <param name="optionsClasses">The options classes to generate content for.</param>
    /// <returns>The .env file content.</returns>
    public string Generate(List<OptionsClassInfo> optionsClasses)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by BuildingBlocks.Tools");
        sb.AppendLine();

        foreach (var optionsClass in optionsClasses.OrderBy(c => c.SectionName))
        {
            sb.AppendLine($"# {optionsClass.SectionName}");
            sb.AppendLine();

            foreach (var property in optionsClass.Properties.OrderBy(p => p.Name))
            {
                var sectionName = optionsClass.SectionName.Replace(":", "__");
                var key = $"{sectionName}__{property.Name}".ToUpperInvariant();
                var value = property.DefaultValue ?? "";

                sb.AppendLine($"{key}={value}");
            }

            sb.AppendLine();
        }

        return sb.ToString();
    }
}
